# Generated by Django 4.0.6 on 2022-12-13 15:34

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('available', 'В наличии'), ('oreder', 'Под заказ'), ('waiting', 'Ожидается поступление'), ('not_availabel', 'Нет в наличии'), ('not_produced', 'Не производится')], max_length=100, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('barcode', models.CharField(max_length=100, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to=shop.models.upload_to, verbose_name='Фото')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['title'],
            },
        ),
    ]
