# Generated by Django 4.1.1 on 2022-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "В наличии"),
                    ("oreder", "Под заказ"),
                    ("waiting", "Ожидается поступление"),
                    ("not_availabel", "Нет в наличии"),
                    ("not_produced", "Не производится"),
                ],
                max_length=100,
                verbose_name="Статус",
            ),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
